### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by shreyasbharath** [tfc/pprintpp#14]
I just wanted to say, thank you for this awesome library ❤️ . This is such an awesome addition for embedded projects where the cost of a printf bug is high and we've been caught out by it many times.

I was thinking of implementing something like this myself but then I came across this after some searching. Once we start using it a lot, you'll probably see PRs coming through from us :)

**Comment by tfc** [comment]
@shreyasbharath Awesome, how pleasant!

This library is in active use, so i will be happy to incorporate fixes/suggestions.

**Comment by shreyasbharath** [comment]
Fantastic, look forward to more awesome improvements!
