### ISSUE TITLE
Explicit hexadecimal format with signed argument

### ISSUE THREAD

**Issue by borisxm** [tfc/pprintpp#3]
Current implementation, silently replaces hexadecimal specifier with decimal one in the case of signed argument. Eg, ```pprintfpp("{x}", 1)``` translates to ```printf("%d", 1)``` which is somewhat unexpected. In my opinion, it is better to have the "%x", as it doesn't break anything and does what the user asked for.

**Comment by tfc** [comment]
Sorry, did not see this earlier. This is fixed with 47e472cd139149dade84091fa75023afacfe7229
